#!/bin/sh

test_fmt() {
    hash gofmt 2>&- || { echo >&2 "Need to check that files are properly formatted prior to commit, but the required gofmt tool is not in PATH."; exit 1; }
    IFS='
'
    for file in `git diff --cached --name-only --diff-filter=ACM | grep '\.go$'`
    do
        output=`git cat-file -p :$file | gofmt -l 2>&1`
        if test $? -ne 0
        then
            output=`echo "$output" | sed "s,<standard input>,$file,"`
            syntaxerrors="${list}${output}\n"
        elif test -n "$output"
        then
            list="${list}${file}\n"
        fi
    done
    exitcode=0
    if test -n "$syntaxerrors"
    then
        echo -e >&2 "\ncommit aborted because gofmt detected problems"
        echo >&2 "gofmt found syntax errors:"
        printf "$syntaxerrors"
        exitcode=1
    fi
    if test -n "$list"
    then
        echo -e >&2 "\ncommit aborted because gofmt detected problems"
        echo >&2 "improperly formatted GO source files found. Run gofmt to fix the format or fix your editor settings to format (run gofmt -w and git add):"
        printf "$list"
        exitcode=1
    fi
    exit $exitcode
}

case "$1" in
    --about )
        echo "Check Go code formatting"
        ;;
    * )
        test_fmt
        ;;
esac
