// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -DAUTOTOOLS_BUILD -DSYSTEM_TYPE_LINUX -DSYSTEM_DEBUG_LEVEL=0 -pthread -D_GNU_SOURCE -I/home/michael_e_brown/15g/build/14g-EC/xrev/tmp/work/armv7a-poky-linux-gnueabi/libgo-dmobj/1.0+git246+4ffe4f374fb9f9962c3176a03886327d42661673-r1.1/recipe-sysroot/usr/include/libdcsgen -I/home/michael_e_brown/15g/build/14g-EC/xrev/tmp/work/armv7a-poky-linux-gnueabi/libgo-dmobj/1.0+git246+4ffe4f374fb9f9962c3176a03886327d42661673-r1.1/recipe-sysroot/usr/include/libdcsmil -I/home/michael_e_brown/15g/build/14g-EC/xrev/tmp/work/armv7a-poky-linux-gnueabi/libgo-dmobj/1.0+git246+4ffe4f374fb9f9962c3176a03886327d42661673-r1.1/recipe-sysroot/usr/include/libdcsupt/dcsupt -I/home/michael_e_brown/15g/build/14g-EC/xrev/tmp/work/armv7a-poky-linux-gnueabi/libgo-dmobj/1.0+git246+4ffe4f374fb9f9962c3176a03886327d42661673-r1.1/recipe-sysroot/usr/include/libthermalpop/ -I/home/michael_e_brown/15g/build/14g-EC/xrev/tmp/work/armv7a-poky-linux-gnueabi/libgo-dmobj/1.0+git246+4ffe4f374fb9f9962c3176a03886327d42661673-r1.1/recipe-sysroot/usr/include ./dm-object-defs.go

package godefs

import (
	eh "github.com/looplab/eventhorizon"
)

type DM_ObjID struct {
	ObjIDUnion [4]byte
}

const Sizeof_DM_ObjID = 0x4

type DM_DataObjHeader struct {
	ObjSize		uint32
	ObjID		DM_ObjID
	ObjType		uint16
	ObjStatus	uint8
	ObjFlags	uint8
	RefreshInterval	uint8
	ReservedAlign	[3]uint8
}

const Sizeof_DM_DataObjHeader = 0x10

type DM_thp_fan_data_object struct {
	Doh			DM_DataObjHeader
	ObjExtFlags		uint32
	OffsetKey		uint32
	OffsetFanName		uint32
	OffsetVendorName	uint32
	OffsetDeviceName	uint32
	OffsetTachName		uint32
	Powerstate		uint8
	Fanhealth		uint8
	Numrotors		uint8
	Int			int8
	Fanpwm			float32
	Rotor1rpm		int32
	Rotor2rpm		int32
	CriticalThreshold	int32
	WarningThreshold	int32
	FanStateMask		uint32
}


const (
	FanEvent 	= eh.EventType("thp_fan_data_object")
)
const Sizeof_DM_thp_fan_data_object = 0x44

func init() {

	eh.RegisterEventData(FanEvent, func() eh.EventData {
		return &DMObject{
			Data: &DM_thp_fan_data_object{},
		}
	})

}

// SOURCE MD5SUM: 7e64bd0c79b50c82cb46bf1c23130e12  ./dm-object-defs.go

