// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs ./hello.go

package godefs

import (
	eh "github.com/looplab/eventhorizon"
)

type HelloEventData struct {
	I		int32
	J		int64
	Message		[10]int8
	Pad_cgo_0	[6]byte
}

const Sizeof_HelloEventData = 0x20

const (
	HelloEvent = eh.EventType("HelloEvent")
)

func init() {
	eh.RegisterEventData(HelloEvent, func() eh.EventData { return &HelloEventData{} })
}
