#!/bin/bash
# only works in go-redfish home dir

set -e
set -x


script_dir=$(cd $(dirname $0); pwd)
cd $script_dir/../..

# for smaller binaries
#go build -ldflags "-s -w" -gcflags="-trimpath=${HOME}" -asmflags="-trimpath=${HOME}"

#generate escape analysis debug output
#GODEBUG= GOGC= go build -o /dev/null -ldflags "-s -w" -gcflags="-trimpath=$PWD -m" -asmflags="-trimpath=$PWD" -tags "idrac pprof" -race -mod=vendor ./cmd/metric-engine



reset
tmux clear-history
reset
if -f [[ data/mrd  ]]
then
  mkdir data/mrd
fi 

cp -R rootfs/factorydir/mrd/* data/mrd/


#GODEBUG= GOGC= go install -ldflags "-s -w" -gcflags="-trimpath=$PWD" -asmflags="-trimpath=$PWD" -tags "json1 pprof redfish sse pipe" -race -mod=vendor ./cmd/metric-engine
GODEBUG= GOGC= go build -ldflags "-s -w" -gcflags="-trimpath=$PWD" -asmflags="-trimpath=$PWD" -tags "json1 pprof redfish sse pipe persistence" -race -mod=vendor ./cmd/metric-engine
export WATCHDOG_USEC=${WATCHDOG_USEC:-100000000}
export GOGC=$GOGC=${GOGC:-65}
export GODEBUG=${GODEBUG:-gctrace=0, memprofilerate=0}
 

./metric-engine 
